// src/pages/problems/_components/Problems.svelte
<script lang="ts">
  import axios from "axios";
  import { onMount } from "svelte";
  import { Search, CheckSquare, Square, Youtube } from "lucide-svelte";
  import type { Users, ProblemList } from "../types";

  let problems: any[] = [];
  export let user: Users | undefined;
  let searchQuery = "";

  console.log("user ", user);
  const difficultyColors = [
    { type: "Hard", color: "text-red-500" },
    { type: "Medium", color: "text-orange-400" },
    { type: "Easy", color: "text-lime-400" },
  ];

  async function getData() {
    console.log("called ");
    try {
      const problemSet = await axios.get("/api/problems");
      console.log("problemSet is ", problemSet);
      problems = problemSet.data || [];
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  }

  const handleProblemClick = (problemId: string, premium = false) => {
    if (user.premiumUser) {
      window.location.href = `/problems/${problemId}`;
    } else {
      if (premium) {
        window.location.href = "/payment";
      } else {
        window.location.href = `/problems/${problemId}`;
      }
    }
  };

  const getDifficultyColor = (difficulty: string) => {
    return difficultyColors.find((d) => d.type === difficulty)?.color || "";
  };

  onMount(() => {
    getData();
  });
</script>

<div>
  <!-- AccountNavbar component would go here -->
  <div class="p-10">
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <div class="p-4 bg-white dark:bg-gray-900">
        <label for="table-search" class="sr-only">Search</label>
        <div class="relative mt-1">
          <div
            class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none"
          >
            <Search class="text-white" size={20} />
          </div>
          <input
            type="text"
            id="table-search"
            bind:value={searchQuery}
            class="block pt-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Search for items"
          />
        </div>
      </div>

      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead
          class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
        >
          <tr>
            <!-- <th scope="col" class="p-4">Status</th> -->
            <th scope="col" class="px-6 py-3">Problem Title</th>
            <th scope="col" class="px-6 py-3">Difficulty</th>
            <th scope="col" class="px-6 py-3">Category</th>

            <th scope="col" class="px-6 py-3">Video Solution</th>
            <th scope="col" class="px-6 py-3">Premium</th>
          </tr>
        </thead>
        <tbody>
          {#each problems.filter((problem) => problem.title
              .toLowerCase()
              .includes(searchQuery.toLowerCase())) as problem}
            <tr
              class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
            >
              <!-- <td class="p-4"> -->
              <!-- { problem.status === 'completed' ? (
                  <CheckSquare class="text-green-500" size={20} />
                ) : (
                  <Square class="text-gray-400" size={20} />
                )} -->
              <!-- </td> -->
              <td
                class="px-6 py-4 cursor-pointer text-blue-600"
                on:click={() =>
                  handleProblemClick(problem.id, problem.isPremium)}
              >
                {problem.title}
              </td>
              <td class={`px-6 py-4 ${getDifficultyColor(problem.difficulty)}`}>
                {problem.difficulty}
              </td>
              <td class="px-6 py-4">
                {problem.category}
              </td>
              <td class="px-6 py-4">
                <!-- {problem.videoSolution ? (
                  <a href={problem.videoSolution} target="_blank">
                    <Youtube class="text-red-500" size={20} />
                  </a>
                ) : (
                  <span class="text-gray-400">N/A</span>
                )} -->
                {#if problem.videoSolution}
                  <a href={problem.videoSolution} target="_blank">
                    <Youtube class="text-red-500" size={20} />
                  </a>
                {:else}
                  <span class="text-gray-400">N/A</span>
                {/if}
              </td>
              <td>
                {#if problem.isPremium}
                  <a href={problem.videoSolution} target="_blank"> Yes </a>
                {:else}
                  <span class="text-gray-400">No</span>
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  </div>
</div>

// src/pages/problems/_components/Problems.tsx
import React, { useState, useEffect } from "react";
import axios from "axios";
import { Search, Crown, ChevronUp, ChevronDown, Youtube } from "lucide-react";
import { actions } from "astro:actions";

const ProblemsList = ({ user }) => {
  const [problems, setProblems] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [sortConfig, setSortConfig] = useState({
    key: null,
    direction: "asc",
  });
  const [selectedDifficulty, setSelectedDifficulty] = useState("all");
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [deletingProblemId, setDeletingProblemId] = useState(null);

  const difficultyColors = {
    Hard: "text-red-500 bg-red-50",
    Medium: "text-orange-500 bg-orange-50",
    Easy: "text-green-500 bg-green-50",
  };

  useEffect(() => {
    

    fetchProblems();
  }, []);
  const fetchProblems = async () => {
    try {
      setIsLoading(true);
      setError(null);
      const response = await axios.get("/api/problems");
      setProblems(response.data || []);
    } catch (err) {
      console.error("Error fetching problems:", err);
      setError("Failed to load problems. Please try again later.");
    } finally {
      setIsLoading(false);
    }
  };

  const getSortedAndFilteredProblems = () => {
    let filteredProblems = [...problems];

    if (searchQuery) {
      filteredProblems = filteredProblems.filter((problem) =>
        problem.title.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }

    if (selectedDifficulty !== "all") {
      filteredProblems = filteredProblems.filter(
        (problem) => problem.difficulty === selectedDifficulty
      );
    }

    if (selectedCategory !== "all") {
      filteredProblems = filteredProblems.filter(
        (problem) => problem.category === selectedCategory
      );
    }

    if (sortConfig.key) {
      filteredProblems.sort((a, b) => {
        if (a[sortConfig.key] < b[sortConfig.key]) {
          return sortConfig.direction === "asc" ? -1 : 1;
        }
        if (a[sortConfig.key] > b[sortConfig.key]) {
          return sortConfig.direction === "asc" ? 1 : -1;
        }
        return 0;
      });
    }

    return filteredProblems;
  };

  const handleSort = (key) => {
    let direction = "asc";
    if (sortConfig.key === key && sortConfig.direction === "asc") {
      direction = "desc";
    }
    setSortConfig({ key, direction });
  };

  const handleProblemClick = (problemId, premium) => {
    if (user?.premiumUser) {
      window.location.href = `/problems/${problemId}`;
    } else {
      if (premium) {
        window.location.href = "/payment";
      } else {
        window.location.href = `/problems/${problemId}`;
      }
    }
  };

  const handleDelete = async (problemId) => {
    try {
      setDeletingProblemId(problemId);
      await actions.setProblemHidden({
        id: problemId,
      });
      await fetchProblems()
    } catch (error) {
      console.error("Error deleting problem:", error);
    } finally {
      setDeletingProblemId(null);
    }
  };

  const categories = [...new Set(problems.map((problem) => problem.category))];

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-4 border-purple-500 border-t-transparent"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <p className="text-red-500 mb-4">{error}</p>
          <button
            onClick={() => window.location.reload()}
            className="px-4 py-2 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  const filteredProblems = getSortedAndFilteredProblems();

  return (
    <div className="p-4 md:p-8 max-w-[80rem] lg:min-w-[60rem] 2xl:min-w-[80rem] mx-auto">
      <div className="mb-6 space-y-4 md:space-y-0 md:flex md:items-center md:justify-between">
        <div className="relative w-full md:w-96">
          <Search
            className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"
            size={20}
          />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search problems..."
            className="w-full pl-10 pr-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-colors"
          />
        </div>

        <div className="flex flex-col md:flex-row gap-4">
          <select
            value={selectedDifficulty}
            onChange={(e) => setSelectedDifficulty(e.target.value)}
            className="px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 focus:border-transparent"
          >
            <option value="all">All Difficulties</option>
            <option value="Easy">Easy</option>
            <option value="Medium">Medium</option>
            <option value="Hard">Hard</option>
          </select>

          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="px-4 py-2 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 focus:border-transparent"
          >
            <option value="all">All Categories</option>
            {categories.map((category) => (
              <option key={category} value={category}>
                {category}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm overflow-hidden border border-gray-100">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="bg-gray-50">
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">
                  <button
                    onClick={() => handleSort("title")}
                    className="flex items-center gap-2 hover:text-purple-600"
                  >
                    Problem Title
                    {sortConfig.key === "title" &&
                      (sortConfig.direction === "asc" ? (
                        <ChevronUp size={16} />
                      ) : (
                        <ChevronDown size={16} />
                      ))}
                  </button>
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">
                  Difficulty
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">
                  Category
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">
                  Resources
                </th>
                {user.admin === "Y" && (
                  <th className="px-6 py-4 text-left text-sm font-semibold text-gray-600">
                    Delete
                  </th>
                )}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filteredProblems.map((problem) => (
                <tr
                  key={problem.id}
                  className="hover:bg-gray-50 transition-colors"
                >
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() =>
                          handleProblemClick(problem.id, problem.isPremium)
                        }
                        className="text-blue-600 hover:text-blue-800 font-medium"
                      >
                        {problem.title}
                      </button>
                      {problem.isPremium && (
                        <Crown className="text-yellow-500" size={16} />
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`px-3 py-1 rounded-full text-sm font-medium ${
                        difficultyColors[problem.difficulty]
                      }`}
                    >
                      {problem.difficulty}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <span className="text-gray-700">{problem.category}</span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-4">
                      {problem.videoSolution ? (
                        <a
                          href={problem.videoSolution}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-red-500 hover:text-red-600 transition-colors"
                        >
                          <Youtube size={20} />
                        </a>
                      ) : (
                        <span className="text-gray-400 text-sm">No video</span>
                      )}
                    </div>
                  </td>
                  {user.admin === "Y" && (
                    <td className="px-6 py-4">
                      <div
                        onClick={() => !deletingProblemId && handleDelete(problem.id)}
                        className={`text-white text-center w-[100px] p-2 cursor-pointer rounded-[4px] ${
                          deletingProblemId === problem.id
                            ? "bg-gray-400 cursor-not-allowed"
                            : "bg-red-500 hover:bg-red-600"
                        }`}
                      >
                        {deletingProblemId === problem.id ? (
                          <div className="flex items-center justify-center gap-2">
                            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                            <span>Deleting...</span>
                          </div>
                        ) : (
                          "Delete"
                        )}
                      </div>
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {filteredProblems.length === 0 && (
        <div className="text-center py-12">
          <p className="text-gray-500">
            No problems found. Try adjusting your filters.
          </p>
        </div>
      )}
    </div>
  );
};

export default ProblemsList;
